# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MotionTool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 677)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 731, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headPitchLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headPitchLabel.setObjectName("headPitchLabel")
        self.verticalLayout_3.addWidget(self.headPitchLabel)
        self.headPitchBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.headPitchBox.setDecimals(3)
        self.headPitchBox.setObjectName("headPitchBox")
        self.verticalLayout_3.addWidget(self.headPitchBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headYawLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headYawLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headYawLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headYawLabel.setObjectName("headYawLabel")
        self.verticalLayout_2.addWidget(self.headYawLabel)
        self.headYawBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.headYawBox.setDecimals(3)
        self.headYawBox.setObjectName("headYawBox")
        self.verticalLayout_2.addWidget(self.headYawBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 380, 691, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.kneePitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.kneePitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.kneePitchLabelRight.setObjectName("kneePitchLabelRight")
        self.verticalLayout_4.addWidget(self.kneePitchLabelRight)
        self.kneePitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.kneePitchRightBox.setDecimals(3)
        self.kneePitchRightBox.setObjectName("kneePitchRightBox")
        self.verticalLayout_4.addWidget(self.kneePitchRightBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.kneePitchLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.kneePitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.kneePitchLabelLeft.setObjectName("kneePitchLabelLeft")
        self.verticalLayout_5.addWidget(self.kneePitchLabelLeft)
        self.kneePitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.kneePitchLeftBox.setDecimals(3)
        self.kneePitchLeftBox.setObjectName("kneePitchLeftBox")
        self.verticalLayout_5.addWidget(self.kneePitchLeftBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(190, 580, 89, 25))
        self.clearButton.setObjectName("clearButton")
        self.setButton = QtWidgets.QPushButton(self.centralwidget)
        self.setButton.setGeometry(QtCore.QRect(350, 580, 89, 25))
        self.setButton.setObjectName("setButton")
        self.pos0Button = QtWidgets.QPushButton(self.centralwidget)
        self.pos0Button.setGeometry(QtCore.QRect(510, 580, 89, 25))
        self.pos0Button.setObjectName("pos0Button")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 470, 731, 76))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ankleRollLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.ankleRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.ankleRollLabelRight.setObjectName("ankleRollLabelRight")
        self.verticalLayout_8.addWidget(self.ankleRollLabelRight)
        self.ankleRollRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.ankleRollRightBox.setDecimals(3)
        self.ankleRollRightBox.setObjectName("ankleRollRightBox")
        self.verticalLayout_8.addWidget(self.ankleRollRightBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.anklePitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.anklePitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.anklePitchLabelRight.setObjectName("anklePitchLabelRight")
        self.verticalLayout_9.addWidget(self.anklePitchLabelRight)
        self.anklePitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.anklePitchRightBox.setDecimals(3)
        self.anklePitchRightBox.setObjectName("anklePitchRightBox")
        self.verticalLayout_9.addWidget(self.anklePitchRightBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.anklePitchLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.anklePitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.anklePitchLabelLeft.setObjectName("anklePitchLabelLeft")
        self.verticalLayout_10.addWidget(self.anklePitchLabelLeft)
        self.anklePitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.anklePitchLeftBox.setDecimals(3)
        self.anklePitchLeftBox.setObjectName("anklePitchLeftBox")
        self.verticalLayout_10.addWidget(self.anklePitchLeftBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ankleRollLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.ankleRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.ankleRollLabelLeft.setObjectName("ankleRollLabelLeft")
        self.verticalLayout_11.addWidget(self.ankleRollLabelLeft)
        self.ankleRollLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.ankleRollLeftBox.setDecimals(3)
        self.ankleRollLeftBox.setObjectName("ankleRollLeftBox")
        self.verticalLayout_11.addWidget(self.ankleRollLeftBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(70, 280, 691, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.hipPitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipPitchLabelRight.setObjectName("hipPitchLabelRight")
        self.verticalLayout_12.addWidget(self.hipPitchLabelRight)
        self.hipPitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipPitchRightBox.setDecimals(3)
        self.hipPitchRightBox.setObjectName("hipPitchRightBox")
        self.verticalLayout_12.addWidget(self.hipPitchRightBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.hipRollLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipRollLabelRight.setObjectName("hipRollLabelRight")
        self.verticalLayout_18.addWidget(self.hipRollLabelRight)
        self.hipRollRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipRollRightBox.setDecimals(3)
        self.hipRollRightBox.setObjectName("hipRollRightBox")
        self.verticalLayout_18.addWidget(self.hipRollRightBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.hipYawLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipYawLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipYawLabelRight.setObjectName("hipYawLabelRight")
        self.verticalLayout_19.addWidget(self.hipYawLabelRight)
        self.hipYawRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipYawRightBox.setDecimals(3)
        self.hipYawRightBox.setObjectName("hipYawRightBox")
        self.verticalLayout_19.addWidget(self.hipYawRightBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.hipYawLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipYawLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipYawLabelLeft.setObjectName("hipYawLabelLeft")
        self.verticalLayout_16.addWidget(self.hipYawLabelLeft)
        self.hipYawLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipYawLeftBox.setDecimals(3)
        self.hipYawLeftBox.setObjectName("hipYawLeftBox")
        self.verticalLayout_16.addWidget(self.hipYawLeftBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.hipRollLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipRollLabelLeft.setObjectName("hipRollLabelLeft")
        self.verticalLayout_17.addWidget(self.hipRollLabelLeft)
        self.hipRollLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipRollLeftBox.setDecimals(3)
        self.hipRollLeftBox.setObjectName("hipRollLeftBox")
        self.verticalLayout_17.addWidget(self.hipRollLeftBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.hipPitchLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.hipPitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipPitchLabelLeft.setObjectName("hipPitchLabelLeft")
        self.verticalLayout_13.addWidget(self.hipPitchLabelLeft)
        self.hipPitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.hipPitchLeftBox.setDecimals(3)
        self.hipPitchLeftBox.setObjectName("hipPitchLeftBox")
        self.verticalLayout_13.addWidget(self.hipPitchLeftBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(70, 150, 691, 71))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.elbowPitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.elbowPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.elbowPitchLabelRight.setObjectName("elbowPitchLabelRight")
        self.verticalLayout_20.addWidget(self.elbowPitchLabelRight)
        self.elbowPitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.elbowPitchRightBox.setDecimals(3)
        self.elbowPitchRightBox.setObjectName("elbowPitchRightBox")
        self.verticalLayout_20.addWidget(self.elbowPitchRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.shoulderRollLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderRollLabelRight.setObjectName("shoulderRollLabelRight")
        self.verticalLayout_21.addWidget(self.shoulderRollLabelRight)
        self.shoulderRollRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderRollRightBox.setDecimals(3)
        self.shoulderRollRightBox.setObjectName("shoulderRollRightBox")
        self.verticalLayout_21.addWidget(self.shoulderRollRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.shoulderPitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderPitchLabelRight.setObjectName("shoulderPitchLabelRight")
        self.verticalLayout_22.addWidget(self.shoulderPitchLabelRight)
        self.shoulderPitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderPitchRightBox.setDecimals(3)
        self.shoulderPitchRightBox.setObjectName("shoulderPitchRightBox")
        self.verticalLayout_22.addWidget(self.shoulderPitchRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.shoulderPitchLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderPitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderPitchLabelLeft.setObjectName("shoulderPitchLabelLeft")
        self.verticalLayout_23.addWidget(self.shoulderPitchLabelLeft)
        self.shoulderPitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderPitchLeftBox.setDecimals(3)
        self.shoulderPitchLeftBox.setObjectName("shoulderPitchLeftBox")
        self.verticalLayout_23.addWidget(self.shoulderPitchLeftBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.shoulderRollLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderRollLabelLeft.setObjectName("shoulderRollLabelLeft")
        self.verticalLayout_24.addWidget(self.shoulderRollLabelLeft)
        self.shoulderRollLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderRollLeftBox.setDecimals(3)
        self.shoulderRollLeftBox.setObjectName("shoulderRollLeftBox")
        self.verticalLayout_24.addWidget(self.shoulderRollLeftBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.elbowPitchLabeLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.elbowPitchLabeLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.elbowPitchLabeLeft.setObjectName("elbowPitchLabeLeft")
        self.verticalLayout_25.addWidget(self.elbowPitchLabeLeft)
        self.elbowPitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.elbowPitchLeftBox.setDecimals(3)
        self.elbowPitchLeftBox.setObjectName("elbowPitchLeftBox")
        self.verticalLayout_25.addWidget(self.elbowPitchLeftBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_25)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion Tool"))
        self.headPitchLabel.setText(_translate("MainWindow", "Head pitch"))
        self.headYawLabel.setText(_translate("MainWindow", "Head yaw"))
        self.kneePitchLabelRight.setText(_translate("MainWindow", "Knee pitch"))
        self.kneePitchLabelLeft.setText(_translate("MainWindow", "Knee pitch"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.setButton.setText(_translate("MainWindow", "Set"))
        self.pos0Button.setText(_translate("MainWindow", "Pos 0"))
        self.ankleRollLabelRight.setText(_translate("MainWindow", "Ankle roll"))
        self.anklePitchLabelRight.setText(_translate("MainWindow", "Ankle pitch"))
        self.anklePitchLabelLeft.setText(_translate("MainWindow", "Ankle pitch"))
        self.ankleRollLabelLeft.setText(_translate("MainWindow", "Ankle roll"))
        self.hipPitchLabelRight.setText(_translate("MainWindow", "Hip pitch"))
        self.hipRollLabelRight.setText(_translate("MainWindow", "Hip roll"))
        self.hipYawLabelRight.setText(_translate("MainWindow", "Hip yaw"))
        self.hipYawLabelLeft.setText(_translate("MainWindow", "Hip yaw"))
        self.hipRollLabelLeft.setText(_translate("MainWindow", "Hip roll"))
        self.hipPitchLabelLeft.setText(_translate("MainWindow", "Hip pitch"))
        self.elbowPitchLabelRight.setText(_translate("MainWindow", "Elbow pitch"))
        self.shoulderRollLabelRight.setText(_translate("MainWindow", "Shoulder roll"))
        self.shoulderPitchLabelRight.setText(_translate("MainWindow", "Shoulder pitch"))
        self.shoulderPitchLabelLeft.setText(_translate("MainWindow", "Shoulder pitch"))
        self.shoulderRollLabelLeft.setText(_translate("MainWindow", "Shoulder roll"))
        self.elbowPitchLabeLeft.setText(_translate("MainWindow", "Elbow pitch"))

